<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <Version>0.0.0</Version>
        <TargetFramework>net10.0</TargetFramework>
        <Title>OpenRpg.Genres.Scifi</Title>
        <Authors>Grofit (LP)</Authors>
        <PackageLicenseUrl>https://github.com/openrpg/OpenRpg.Genres/blob/master/LICENSE</PackageLicenseUrl>
        <PackageProjectUrl>https://github.com/openrpg/OpenRpg.Genres</PackageProjectUrl>
        <Description>Adds common types and classes for scifi/space ship related game types</Description>
        <PackageTags>rpg game-development xna monogame unity godot</PackageTags>
        <LangVersion>14</LangVersion>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\OpenRpg.Genres\OpenRpg.Genres.csproj" />
    </ItemGroup>

    <ItemGroup>
        <EmbeddedResource Include="manifest.json" />
    </ItemGroup>

</Project>
