<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <OutputType>WinExe</OutputType>
        <TargetFramework>net9.0-windows</TargetFramework>
        <RollForward>Major</RollForward>
        <PublishReadyToRun>false</PublishReadyToRun>
        <TieredCompilation>false</TieredCompilation>
        <UseWindowsForms>true</UseWindowsForms>
    </PropertyGroup>
    <PropertyGroup>
        <ApplicationManifest>app.manifest</ApplicationManifest>
        <ApplicationIcon>Icon.ico</ApplicationIcon>
    </PropertyGroup>
    <ItemGroup>
        <PackageReference Include="Gum.MonoGame" Version="2026.5.8.1" />
        <PackageReference Include="MonoGame.Framework.WindowsDX" Version="3.8.*"/>
        <PackageReference Include="MonoGame.Content.Builder.Task" Version="3.8.*"/>
    </ItemGroup>
    <ItemGroup>
      <Folder Include="Content\Project\" />
    </ItemGroup>
</Project>